listing/urls.py
from .models import *
from .views import *
from django import views
from django.urls import path

app_name = 'listing'

urlpatterns = [
    path('', index, name='home'),
    path('<int:list_id>', detailed, name='detailed'),
    path('contact', contact_view, name='contact'),

]

realestate/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("listing.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listing/models.py
from django.db import models

class Listings(models.Model):
    Title = models.CharField(max_length=100,null=False)
    Address = models.TextField(max_length=250,null=False)
    Area = models.IntegerField(null=True)
    Description = models.TextField()
    media = models.ImageField(upload_to="media",null=False)

    def __str__(self):
         return self.Title


class Contact(models.Model):
    name = models.CharField(max_length=40,null=True)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=10,null=False)
    enquiry = models.ForeignKey(Listings, on_delete=models.CASCADE,null=True)
    message = models.TextField(max_length=250)
    Address = models.TextField(max_length=250)

 
    def __str__(self):
            return self.name

            
        

listing/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name','email','phone','message','Address']

listing/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import ContactForm
from .models import *


def index(request):
    listings = Listings.objects.all()
    return render(request, 'index.html',{'listings':listings})


def detailed(request,list_id):
    listing = Listings.objects.get(pk=list_id)
    if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                contact = form.save(commit=False)
                contact.listing = listing
                form.save()  # Save the form data to the Contact model
                return HttpResponse("Success")  # Redirect to a success page
    else:
        form = ContactForm(initial={'enquiry': listing})
    context = {
        'listing':listing,
        'form': form,
    }
    return render(request,'detail.html',context)

        
        



def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()  # Save the form data to the Contact model
            return HttpResponse("Success")  # Redirect to a success page
    else:
        form = ContactForm()
    context = {'form': form}
    return render(request, 'contact.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Destiny Real Estate Listings</title>

    {% include 'partials/header.html' %}
</head>
<body class="gray-bg">
{% include 'partials/navbar.html' %}

{% block content %}{% endblock %}

{% comment %} {% include 'partials/footer.html' %}
{% include 'partials/scripts.html' %} {% endcomment %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}

<h1>Contact Form</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Detailed View</h1>
<h1>{{ listing.Title }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>


<a href="{% url 'listing:contact' %}">Contact Us</a>
{% endblock  %}

templates/index.html
{% extends 'base.html' %}
{% block content %}


<h1>Real Estate Listings</h1>
{% comment %} <ul>
    <li>

<h1>{{ listings.id }} ) {{listings.Title }}</h1>
<h3>{{ listings.Address }}</h3>
<p>{{listings.Description }}</p>
<img src="{{ listings.media }}" alt="{{listings.Title}}">
<a href="{% url 'listing:detailed' listings.id %}">View</a> 

<hr><br>

    </li>
</ul> {% endcomment %}


      

<div class="container d-flex justify-content-center mt-50 mb-50">
    
    <div class="row">
       <div class="col-md-10">
        {% for listings in listings %}
            <div class="card card-body mt-3">
                        <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
                            <div class="mr-2 mb-3 mb-lg-0">
                                
                                    <img src="{{listings.media.url}}" width="150" height="150" alt="">
                               
                            </div>

                            <div class="media-body">
                                <h6 class="media-title font-weight-semibold">
                                    <a href="#" data-abc="true">{{listings.Title}}</a>
                                </h6>

                                <ul class="list-inline list-inline-dotted mb-3 mb-lg-2">
                                    <li class="list-inline-item"><a href="#" class="text-muted" data-abc="true">Phones</a></li>
                                    <li class="list-inline-item"><a href="#" class="text-muted" data-abc="true">Mobiles</a></li>
                                </ul>

                                <p class="mb-3">{{listings.Description}}</p>

                                <ul class="list-inline list-inline-dotted mb-0">
                                    <li class="list-inline-item">All items from <a href="#" data-abc="true">Mobile junction</a></li>
                                    <li class="list-inline-item">Add to <a href="#" data-abc="true">wishlist</a></li>
                                </ul>
                            </div>

                            <div class="mt-3 mt-lg-0 ml-lg-3 text-center">
                                <h3 class="mb-0 font-weight-semibold">{{listings.Area}} Acre</h3>

                                <div>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>

                                </div>

                                <div class="text-muted">2349 reviews</div>

                                <button type="button" class="btn btn-warning mt-4 text-white"><i class="icon-cart-add mr-2"></i> Add to cart</button>
                            </div>
                        </div>
                    </div> 
                    {% endfor %}
                   

{% endblock %}

templates/partials/header.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">